package com.example.learning.threads

val TLH_ADD = 1
val TLH_SUBTRACT = 2
val TLH_RESULT = 3

val TLH_ADDITION_SUCCESS = 4
val TLH_ADDITION_FAIL = 5

val TLH_SUBTRACTION_SUCCESS = 6
val TLH_SUBTRACTION_FAIL = 7

val HT_ADDITION_SUCCESS = 8